CanalTP\SamCoreBundle\Entity\Application:
    type: entity
    table: tr_application_app
    repositoryClass: CanalTP\SamCoreBundle\Entity\ApplicationRepository
    fields:
        id:
            type: integer
            id: true
            column: app_id
            generator:
                strategy: AUTO
        name:
            type: string
            column: app_name
            length: 255
        defaultRoute:
            type: string
            column: app_defaultroute
            length: 255
            nullable: true
        canonicalName:
            type: string
            column: app_canonicalname
            length: 255
            nullable: true
    oneToMany:
        applicationRoles:
            targetEntity: CanalTP\SamCoreBundle\Entity\ApplicationRole
            mappedBy: application
            cascade:
               - persist
    manyToMany:
        users:
            targetEntity: CanalTP\SamEcoreUserManagerBundle\Entity\User
            mappedBy: groups
            cascade:
               - persist
    lifecycleCallbacks:
        postLoad:
            - onPostLoad
