CanalTP\SamCoreBundle\Entity\ApplicationRole:
    type: entity
    table: tj_application_role
    repositoryClass: CanalTP\SamCoreBundle\Entity\ApplicationRoleRepository
    fields:
        id:
            type: integer
            id: true
            column: apr_id
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        canonicalRole:
            type: string
            length: '100'
        permissions:
            type: array
            nullable: true
    manyToOne:
        application:
            targetEntity: CanalTP\SamCoreBundle\Entity\Application
            inversedBy: roles
            joinColumn:
                name: app_id
                referencedColumnName: app_id
        role:
            targetEntity: CanalTP\SamCoreBundle\Entity\Role
            inversedBy: applicationRoles
            joinColumn:
                name: rol_id
                referencedColumnName: id
    manyToMany:
        users:
            targetEntity: CanalTP\SamEcoreUserManagerBundle\Entity\User
            mappedBy: applicationRoles
            cascade:
               - persist
    lifecycleCallbacks: {  }
