CanalTP\SamCoreBundle\Entity\Application:
    type: entity
    table: public.tr_application_app
    repositoryClass: CanalTP\SamCoreBundle\Entity\ApplicationRepository
    fields:
        id:
            type: integer
            id: true
            column: app_id
            generator:
                strategy: IDENTITY
        name:
            type: string
            column: app_name
            length: 255
        canonicalName:
            type: string
            column: app_canonical_name
            length: 255
        defaultRoute:
            type: string
            column: app_default_route
            length: 255
            nullable: true
        bundleName:
            type: string
            column: app_bundle_name
            length: 255
            nullable: true
    oneToMany:
        roles:
            targetEntity: CanalTP\SamCoreBundle\Entity\Role
            mappedBy: application
        customers:
            targetEntity: CanalTP\SamCoreBundle\Entity\CustomerApplication
            mappedBy: application
