CanalTP\SamCoreBundle\Entity\Client:
    type: entity
    table: public.tr_client_cli
    repositoryClass: CanalTP\SamCoreBundle\Entity\ClientRepository
    fields:
        id:
            type: integer
            id: true
            column: cli_id
            generator:
                strategy: SEQUENCE
        name:
            type: string
            column: cli_name
            length: 255
            nullable: false
        nameCanonical:
            type: string
            column: cli_name_canonical
            length: 255
            nullable: false
        logoPath:
            type: string
            column: cli_logo_path
            length: 255
            nullable: true
        locked:
            type: boolean
            column: cli_locked
            nullable: false
        creationDateTime:
            type: datetime
            column: cli_creation_datetime
            nullable: false
        lastModificationDateTime:
            type: datetime
            column: cli_last_modification_datetime
            nullable: false
    uniqueConstraints:
        name_idx:
            columns: [ cli_name_canonical ]
    oneToMany:
        perimeters:
            targetEntity: CanalTP\SamCoreBundle\Entity\Perimeter
            mappedBy: client
            cascade: [persist]
        applications:
            targetEntity: CanalTP\SamCoreBundle\Entity\ClientApplication
            mappedBy: client
        users:
            targetEntity: CanalTP\SamEcoreUserManagerBundle\Entity\User
            mappedBy: client
