CanalTP\IussaadCoreBundle\Entity\CoBranding:
    type: entity
    table: CoBranding
    repositoryClass: CanalTP\IussaadCoreBundle\Entity\CoBrandingRepository
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: SEQUENCE
        company:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        firstname:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        lastname:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        address:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        motivation:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        domaine:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        email:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        job:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        key:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        createdAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: created_at
        updatedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: updated_at
        status:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        sim:
            targetEntity: CanalTP\IussaadCoreBundle\Entity\Sim
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sim_id:
                    referencedColumnName: sim_id
            orphanRemoval: false
    lifecycleCallbacks:
        prePersist:
            - onPrePersist
        preUpdate:
            - onPreUpdate
