CanalTP\SamCoreBundle\Entity\Perimeter:
    type: entity
    table: public.t_perimeter_per
    repositoryClass: CanalTP\SamCoreBundle\Entity\PerimeterRepository
    id:
        id:
            type: integer
            id: true
            column: per_id
            generator:
                strategy: AUTO
    fields:
        externalCoverageId:
            type: string
            length: 255
            column: per_external_coverage_id
        externalNetworkId:
            type: string
            length: 255
            column: per_external_network_id
    uniqueConstraints:
        customer_id_external_coverage_id_external_network_id_idx:
            columns: [ cus_id, per_external_coverage_id, per_external_network_id ]
    manyToOne:
        customer:
            targetEntity: CanalTP\SamCoreBundle\Entity\Customer
            inversedBy: perimeters
            joinColumn:
                name: cus_id
                referencedColumnName: cus_id
    lifecycleCallbacks: {  }
