CanalTP\SamCoreBundle\Entity\Role:
    type: entity
    table: t_role_rol
    repositoryClass: CanalTP\SamCoreBundle\Entity\RoleRepository
    fields:
        id:
            column: rol_id
            type: integer
            id: true
            generator:
                strategy: IDENTITY
        name:
            type: string
            column: rol_name
            length: 255
        canonicalName:
            type: string
            column: rol_name_canonical
            length: 255
        permissions:
            type: array
            column: rol_permissions
            nullable: true
    manyToOne:
        application:
            targetEntity: CanalTP\SamCoreBundle\Entity\Application
            inversedBy: roles
            joinColumn:
                name: app_id
                referencedColumnName: app_id
    oneToMany:
        userApplications:
            targetEntity: CanalTP\SamCoreBundle\Entity\UserApplicationRole
            mappedBy: role
            cascade: ["persist", "merge"]
    lifecycleCallbacks: {  }
    entityListeners:
        CanalTP\SamCoreBundle\Doctrine\RoleListener:
            preUpdate: [preUpdate]
            prePersist: [prePersist]
