CanalTP\IussaadCoreBundle\Entity\Sim:
    type: entity
    table: t_sim_sim
    repositoryClass: CanalTP\IussaadCoreBundle\Entity\SimRepository
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            column: sim_id
            generator:
                strategy: SEQUENCE
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
            column: sim_name
        nameCanonical:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
            column: sim_namecanonical
        url:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
            column: sim_url
        createDate:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: sim_createdate
        updateDate:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: sim_updatedate
        networks:
            type: array
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: sim_networks
    manyToOne:
        status:
            targetEntity: CanalTP\IussaadCoreBundle\Entity\Status
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sst_id:
                    referencedColumnName: sst_id
            orphanRemoval: false
    oneToMany:
        sim_commercial_modes:
            targetEntity: CanalTP\IussaadCoreBundle\Entity\SimMode
            cascade:
                - persist
            mappedBy: sim
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks:
        prePersist:
            - onPrePersist
        preUpdate:
            - onPreUpdate
