CanalTP\IussaadCoreBundle\Entity\SimMode:
    type: entity
    table: tj_simmode_smd
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            column: smd_id
            generator:
                strategy: SEQUENCE
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
            column: smd_name
        available:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: smd_available
        visible:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: smd_visible
        includeByDefault:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: smd_includeByDefault
        createDate:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: sim_createdate
        updateDate:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: sim_updatedate
    manyToOne:
        sim:
            targetEntity: CanalTP\IussaadCoreBundle\Entity\Sim
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sim_id:
                    referencedColumnName: sim_id
            orphanRemoval: false
        mode:
            targetEntity: CanalTP\IussaadCoreBundle\Entity\Mode
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                mde_id:
                    referencedColumnName: mde_id
            orphanRemoval: false
    lifecycleCallbacks:
        postPersist:
            - upload
        postUpdate:
            - upload
        postRemove:
            - removeUpload
        prePersist:
            - onPrePersist
        preUpdate:
            - onPreUpdate
