CanalTP\SamCoreBundle\Entity\Status:
    type: entity
    table: tr_simstatus_sst
    repositoryClass: CanalTP\SamCoreBundle\Entity\StatusRepository
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            column: sst_id
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
            column: sst_name
    lifecycleCallbacks: {  }
