canal_tp_sam_homepage:
    pattern:  /
    defaults: { _controller: CanalTPSamCoreBundle:Sam:index }

sam_client_list:
    pattern:  /client
    defaults: { _controller: CanalTPSamCoreBundle:Client:list }

sam_client_new:
    pattern:  /client/new
    defaults: { _controller: CanalTPSamCoreBundle:Client:new }

sam_client_edit:
    pattern:  /client/{id}/edit
    defaults: { _controller: CanalTPSamCoreBundle:Client:edit }
