parameters:
    sam_core.slugify.class: CanalTP\SamCoreBundle\Slugify
    sam_core.role_listener.class: CanalTP\SamCoreBundle\Doctrine\RoleListener
    sam_core.doctrine.entity_listener_resolver.class: CanalTP\SamCoreBundle\Doctrine\EntityListenerResolver

services:
    sam_core.slugify:
        class: %sam_core.slugify.class%

    sam_core.role_listener:
        class: %sam_core.role_listener.class%
        arguments: ['@sam_core.slugify']
        tags:
            -  { name: doctrine.entity_listener }

    sam_core.doctrine.entity_listener_resolver:
        class: %sam_core.doctrine.entity_listener_resolver.class%
        arguments: [ "@service_container" ]
