parameters:
    sam_core.slugify.class: CanalTP\SamCoreBundle\Slugify
    sam_core.role_listener.class: CanalTP\SamCoreBundle\Doctrine\RoleListener
    sam_core.doctrine.entity_listener_resolver.class: CanalTP\SamCoreBundle\Doctrine\EntityListenerResolver

    sam_component_authentication_handler.class: CanalTP\SamCoreBundle\Component\Authentication\Handler\LoginSuccessHandler
    sam_user_registration_listener.class: CanalTP\SamCoreBundle\Form\EventListener\RegistrationSuscriber
    # Monitoring
    sam.business_monitoring.nmm.class: CanalTP\SamCoreBundle\Monitoring\Component
    sam_core.client.class: CanalTP\SamCoreBundle\Services\ClientManager

services:
    sam_core.slugify:
        class: %sam_core.slugify.class%

    sam_core.role_listener:
        class: %sam_core.role_listener.class%
        arguments: ['@sam_core.slugify']
        tags:
            -  { name: doctrine.entity_listener }

    sam_core.doctrine.entity_listener_resolver:
        class: %sam_core.doctrine.entity_listener_resolver.class%
        arguments: [ "@service_container" ]

    sam.component.authentication.handler.login_success_handler:
        class:          "%sam_component_authentication_handler.class%"
        arguments:  ['@doctrine', '@router', '@session']

    # Monitoring
    sam.business_monitoring.nmm:
        class: "%sam.business_monitoring.nmm.class%"
        calls:
            - [ setName, ['Navitia Mobility Manager']]

    nmm.service_monitoring.database.psql:
        class: "%sam.service_monitoring.database.pgsql.class%"
        arguments: [%database_host%, %database_port%, %database_name%, %database_user%, %database_password%]
        tags:
            - { name: service_monitoring, category: Tech }

    nmm.service_monitoring.login:
        class: "%sam.service_monitoring.http.rest.class%"
        arguments: [%monitoring.sam.host%, 'NMM Application', 302]
        tags:
            - { name: service_monitoring, category: Business }

    # Client
    sam_core.client:
        class: %sam_core.client.class%
        arguments: ['@doctrine.orm.entity_manager']
