parameters:
#    canal_tp_iussaad_core.example.class: CanalTP\IussaadCoreBundle\Example

services:
#    canal_tp_iussaad_core.example:
#        class: %canal_tp_iussaad_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
