parameters:
#    canal_tp_sam_core.example.class: CanalTP\SamCoreBundle\Example

services:
#    canal_tp_sam_core.example:
#        class: %canal_tp_sam_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
