CanalTP\IussaadCoreBundle\Entity\CoBranding:
    properties:
        company:
            - NotBlank: ~
        firstname:
            - NotBlank: ~
        lastname:
            - NotBlank: ~
        address:
            - NotBlank: ~
        motivation:
            - NotBlank: ~
        domaine:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
        job:
            - NotBlank: ~
        sim:
            - Type:
                type: CanalTP\IussaadCoreBundle\Entity\Sim
