CanalTP\SamCoreBundle\Entity\Customer:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
CanalTP\SamCoreBundle\Entity\Perimeter:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [customer, externalCoverageId, externalNetworkId]
