CanalTP\SamCoreBundle\Entity\Client:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
CanalTP\SamCoreBundle\Entity\Perimeter:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [client, externalCoverageId, externalNetworkId]
