FROM php:7.0-apache

WORKDIR /app

# Install composer
RUN curl -sS https://getcomposer.org/installer | \
    php -- --install-dir=/usr/bin/ --filename=composer \
    && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yq \
        unzip \
        git \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get autoremove -y

RUN echo 'memory_limit = -1' >> $PHP_INI_DIR/php.ini

# Install internationalization extension
RUN BUILD_DEPS="g++ libicu-dev" && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq \
    $BUILD_DEPS \
	&& docker-php-ext-configure intl \
    && docker-php-ext-install intl \
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false $BUILD_DEPS \
    && rm -rf /var/lib/apt/lists/*

# Install xdebug extension
RUN pecl install \
		xdebug-2.5.0 \
	&& docker-php-ext-enable \
		xdebug

# Install opcache extension
RUN docker-php-ext-install opcache \
    && docker-php-ext-enable opcache \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get autoremove -y
RUN echo 'opcache.max_accelerated_files = 10000' >> /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
RUN echo 'opcache.enable_cli = 1' >> /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini

# Install openssh-client
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq \
    openssh-client \
    && rm -rf /var/lib/apt/lists/*

# Install acl
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq \
    acl \
    && rm -rf /var/lib/apt/lists/*

# Install jq
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq \
    jq \
    && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN BUILD_DEPS="libcurl3-dev g++ libicu-dev zlib1g-dev libxml2-dev zlib1g-dev" \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -yq \
		$BUILD_DEPS \
        libpq-dev \
        libmcrypt-dev \
        libmemcached-dev \
    && docker-php-ext-configure \
		pgsql -with-pgsql=/usr/local/pgsql \
	&& docker-php-ext-install \
		bcmath \
		pgsql \
        curl \
        intl \
        mbstring \
        zip \
        xml \
        sockets \
        mcrypt \
        pcntl \
        pdo \
        pdo_pgsql \
    && pecl install \
        memcached \
    && docker-php-ext-enable \
        memcached \
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false $BUILD_DEPS \
    && rm -rf /var/lib/apt/lists/*

RUN a2enmod rewrite

VOLUME [ "/app" ]
